#!/usr/bin/env node

import { promises as fs } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const ROOT_DIR = path.resolve(__dirname, '..')
const BASE_URL = process.env.SITEMAP_BASE_URL || 'https://kartika.id'

const BLOG_FILE = path.join(ROOT_DIR, 'src', 'data', 'kartika-blog.ts')
const OUTPUT_DIR = path.join(ROOT_DIR, 'public')

const formatDate = (date) => {
  if (!(date instanceof Date) || Number.isNaN(date.getTime())) {
    return new Date().toISOString().split('T')[0]
  }
  return date.toISOString().split('T')[0]
}

const formatDateTime = (date) => {
  if (!(date instanceof Date) || Number.isNaN(date.getTime())) {
    return new Date().toISOString()
  }
  return date.toISOString()
}

const escapeXml = (str) => {
  if (!str) return ''
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

const clampToPastDate = (dateString) => {
  const parsed = new Date(dateString)
  const now = new Date()
  if (Number.isNaN(parsed.getTime())) {
    return now
  }
  return parsed > now ? now : parsed
}

const readFileSafe = async (filePath) => {
  try {
    return await fs.readFile(filePath, 'utf8')
  } catch (error) {
    console.warn(`[sitemap] Unable to read ${filePath}:`, error.message)
    return ''
  }
}

const parseBlogPosts = (source) => {
  const posts = []
  // More robust regex that handles multiline and various spacing
  const regex = /{\s*["']?id["']?:\s*(\d+)[^}]*?["']?slug["']?:\s*['"]([^'"]+)['"][^}]*?["']?title["']?:\s*['"]([^'"]+)['"][^}]*?["']?image["']?:\s*['"]([^'"]+)['"][^}]*?["']?date["']?:\s*['"]([^'"]+)['"][^}]*?}/gs
  let match
  let count = 0
  while ((match = regex.exec(source))) {
    const [, id, slug, title, image, dateString] = match
    posts.push({
      id: parseInt(id),
      slug,
      title: escapeXml(title),
      image: escapeXml(image),
      loc: `${BASE_URL}/blog/${slug}`,
      lastmod: clampToPastDate(dateString),
      changefreq: 'monthly',
      priority: 0.62
    })
    count++
  }
  console.log(`[sitemap] Parsed ${count} blog posts`)
  return posts
}

const getFileLastModified = async (relativePath) => {
  try {
    const stats = await fs.stat(path.join(ROOT_DIR, relativePath))
    return stats.mtime
  } catch (error) {
    console.warn(`[sitemap] Unable to get mtime for ${relativePath}:`, error.message)
    return new Date()
  }
}

const buildStaticPages = async () => {
  const staticPages = [
    { loc: `${BASE_URL}/`, file: 'src/pages/Home.tsx', changefreq: 'weekly', priority: 1.0 },
    { loc: `${BASE_URL}/blog`, file: 'src/pages/KartikaBlog.tsx', changefreq: 'daily', priority: 0.9 },
    { loc: `${BASE_URL}/about`, file: 'src/pages/Home.tsx', changefreq: 'monthly', priority: 0.7 },
  ]

  return Promise.all(staticPages.map(async (page) => ({
    ...page,
    lastmod: await getFileLastModified(page.file)
  })))
}

const buildLanguageAlternates = (loc, explicitAlternates) => {
  if (explicitAlternates && explicitAlternates.length > 0) {
    return explicitAlternates
  }
  return [] // Simplified for Kartika.id, no multi-lang query params required currently
}

// Generate sitemap index (main sitemap.xml)
const generateSitemapIndex = (sitemaps) => {
  const header = '<?xml version="1.0" encoding="UTF-8"?>'
  const stylesheet = '<?xml-stylesheet type="text/xsl" href="/sitemap-index.xsl"?>'
  const comment = '<!-- Generated by Kartika.id Sitemap Generator, this is an XML Sitemap Index, meant for consumption by search engines. -->'
  const openTag = '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
  const closeTag = '</sitemapindex>'

  const entries = sitemaps.map((sitemap) => {
    return [
      '  <sitemap>',
      `    <loc>${escapeXml(sitemap.loc)}</loc>`,
      `    <lastmod>${formatDateTime(sitemap.lastmod)}</lastmod>`,
      '  </sitemap>'
    ].join('\n')
  })

  return [header, stylesheet, comment, openTag, ...entries, closeTag, ''].join('\n')
}

// Generate post sitemap (blog posts with images)
const generatePostSitemap = (posts) => {
  const header = '<?xml version="1.0" encoding="UTF-8"?>'
  const stylesheet = '<?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>'
  const openTag = '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml">'
  const closeTag = '</urlset>'

  const entries = posts.map((post) => {
    const parts = [
      '  <url>',
      `    <loc>${escapeXml(post.loc)}</loc>`,
      `    <lastmod>${formatDate(post.lastmod)}</lastmod>`,
      `    <changefreq>${post.changefreq}</changefreq>`,
      `    <priority>${post.priority.toFixed(2)}</priority>`
    ]

    // Add image tags
    if (post.image) {
      parts.push('    <image:image>')
      parts.push(`      <image:loc>${post.image}</image:loc>`)
      parts.push(`      <image:title>${post.title}</image:title>`)
      parts.push(`      <image:caption>${post.title}</image:caption>`)
      parts.push('    </image:image>')
    }

    // Add language alternates
    const alternates = buildLanguageAlternates(post.loc, post.alternates)
    alternates.forEach((alternate) => {
      if (alternate?.href && alternate?.hrefLang) {
        parts.push(`    <xhtml:link rel="alternate" hreflang="${escapeXml(alternate.hrefLang)}" href="${escapeXml(alternate.href)}" />`)
      }
    })

    parts.push('  </url>')
    return parts.join('\n')
  })

  return [header, stylesheet, openTag, ...entries, closeTag, ''].join('\n')
}

// Generate page sitemap (static pages)
const generatePageSitemap = (pages) => {
  const header = '<?xml version="1.0" encoding="UTF-8"?>'
  const stylesheet = '<?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>'
  const openTag = '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">'
  const closeTag = '</urlset>'

  const entries = pages.map((page) => {
    const parts = [
      '  <url>',
      `    <loc>${escapeXml(page.loc)}</loc>`,
      `    <lastmod>${formatDate(page.lastmod)}</lastmod>`,
      `    <changefreq>${page.changefreq}</changefreq>`,
      `    <priority>${page.priority.toFixed(2)}</priority>`
    ]

    // Add language alternates
    const alternates = buildLanguageAlternates(page.loc, page.alternates)
    alternates.forEach((alternate) => {
      if (alternate?.href && alternate?.hrefLang) {
        parts.push(`    <xhtml:link rel="alternate" hreflang="${escapeXml(alternate.hrefLang)}" href="${escapeXml(alternate.href)}" />`)
      }
    })

    parts.push('  </url>')
    return parts.join('\n')
  })

  return [header, stylesheet, openTag, ...entries, closeTag, ''].join('\n')
}

// Generate attachment sitemap (images from blog)
const generateAttachmentSitemap = (posts) => {
  const header = '<?xml version="1.0" encoding="UTF-8"?>'
  const stylesheet = '<?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>'
  const openTag = '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">'
  const closeTag = '</urlset>'

  const entries = []
  const now = new Date()

  posts.forEach((post) => {
    if (post.image) {
      entries.push([
        '  <url>',
        `    <loc>${escapeXml(post.image)}</loc>`,
        `    <lastmod>${formatDate(now)}</lastmod>`,
        `    <changefreq>monthly</changefreq>`,
        `    <priority>0.50</priority>`,
        '    <image:image>',
        `      <image:loc>${escapeXml(post.image)}</image:loc>`,
        `      <image:title>${escapeXml(post.title)}</image:title>`,
        `      <image:caption>${escapeXml(post.title)}</image:caption>`,
        '    </image:image>',
        '  </url>'
      ].join('\n'))
    }
  })

  return [header, stylesheet, openTag, ...entries, closeTag, ''].join('\n')
}

const main = async () => {
  console.log('[sitemap] Starting sitemap generation...')

  // Read source files
  const [blogSource] = await Promise.all([
    readFileSafe(BLOG_FILE)
  ])

  // Parse data
  const [staticPages, blogPosts] = await Promise.all([
    buildStaticPages(),
    Promise.resolve(parseBlogPosts(blogSource))
  ])

  // Get latest dates for each sitemap
  const latestBlogDate = blogPosts.reduce((latest, entry) => {
    const time = entry.lastmod.getTime()
    return time > latest ? time : latest
  }, 0)

  const latestPageDate = staticPages.reduce((latest, entry) => {
    const time = entry.lastmod.getTime()
    return time > latest ? time : latest
  }, 0)

  const now = new Date()

  // Update blog listing page with latest blog date
  const blogListing = staticPages.find(page => page.loc === `${BASE_URL}/blog`)
  if (blogListing && latestBlogDate) {
    blogListing.lastmod = new Date(latestBlogDate)
  }

  // Generate individual sitemaps
  console.log('[sitemap] Generating post-sitemap.xml...')
  const postSitemapXml = generatePostSitemap(blogPosts.sort((a, b) => b.lastmod.getTime() - a.lastmod.getTime()))
  await fs.writeFile(path.join(OUTPUT_DIR, 'post-sitemap.xml'), postSitemapXml, 'utf8')

  console.log('[sitemap] Generating page-sitemap.xml...')
  const pageSitemapXml = generatePageSitemap(staticPages.sort((a, b) => a.loc.localeCompare(b.loc)))
  await fs.writeFile(path.join(OUTPUT_DIR, 'page-sitemap.xml'), pageSitemapXml, 'utf8')

  console.log('[sitemap] Generating attachment-sitemap.xml...')
  const attachmentSitemapXml = generateAttachmentSitemap(blogPosts)
  await fs.writeFile(path.join(OUTPUT_DIR, 'attachment-sitemap.xml'), attachmentSitemapXml, 'utf8')

  // Generate sitemap index
  console.log('[sitemap] Generating sitemap.xml (index)...')
  const sitemapIndex = [
    {
      loc: `${BASE_URL}/post-sitemap.xml`,
      lastmod: new Date(latestBlogDate || now)
    },
    {
      loc: `${BASE_URL}/page-sitemap.xml`,
      lastmod: new Date(latestPageDate || now)
    },
    {
      loc: `${BASE_URL}/attachment-sitemap.xml`,
      lastmod: now
    }
  ]

  const indexXml = generateSitemapIndex(sitemapIndex)
  await fs.writeFile(path.join(OUTPUT_DIR, 'sitemap.xml'), indexXml, 'utf8')

  console.log('[sitemap] ✓ Generated sitemap index with 3 sitemaps')
  console.log(`[sitemap] ✓ post-sitemap.xml: ${blogPosts.length} blog posts`)
  console.log(`[sitemap] ✓ page-sitemap.xml: ${staticPages.length} pages`)
  console.log(`[sitemap] ✓ attachment-sitemap.xml: ${blogPosts.length} images`)
  console.log('[sitemap] ✓ All sitemaps generated successfully!')
}

main().catch((error) => {
  console.error('[sitemap] Failed to generate sitemaps:', error)
  process.exitCode = 1
})
